### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by LinqLover** [sourcegraph/sourcegraph-open-in-vscode#22]
Win 20H1 / VS Code v1.60.0

Sourcegraph settings:

```json
"vscode.open.basePath": "/C:/Users/Christoph/OneDrive/Dokumente/Codes/downloaded/"
```

Base directory exists:

```pwsh
❯ (Get-Item C:/Users/Christoph/OneDrive/Dokumente/Codes/downloaded/).Exists
True
```

However, when I click the "open in VS Code button" either in a file on searchgraph.com or on GitHub.com with the Sourcegraph browser extension, I receive the following dialogs _(manually translated back from German, error strings might be non-literal_):

Dialog 1:

> [Window Title]
> Visual Studio Code
> 
> [Main Instruction]
> An external application would like to open "C:\Users\Christoph\OneDrive\Dokumente\Codes\downloaded\node\lib\internal\modules\cjs\loader.js:462:21" in Code. Would you like to open this file or folder?
> 
> [Yes] [No]

After clicking Yes:

> [Window Title]
> Visual Studio Code
> 
> [Main Instruction]
> The path does not exist.
> 
> [Content]
> The path "C:\Users\Christoph\OneDrive\Dokumente\Codes\downloaded\node\lib\internal\modules\cjs\loader.js:462:21" is not available on this machine.
> 
> [OK]

I also tried the configuration for WSL (which I would actually prefer):

```json
"vscode.open.basePath": "//wsl$/Ubuntu-18.04/mnt/c/Users/Christoph/OneDrive/Dokumente/Codes/_downloaded",
"vscode.open.uncPath": true
```

Base directory exists:

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
Christoph@Thiede-Spectre /mnt/c/Users/Christoph/OneDrive/Dokumente/Codes
$ file /mnt/c/Users/Christoph/OneDrive/Dokumente/Codes/_downloaded
/mnt/c/Users/Christoph/OneDrive/Dokumente/Codes/_downloaded: directory
```

But then receive the same error for the path `\wsl$\Ubuntu-18.04\mnt\c\Users\Christoph\OneDrive\Dokumente\Codes\_downloaded\node-webworker-threads\.github\workflows\build.yml`.

Did I miss any step in the configuration or do we have a regression here? :-)

**Comment by abeatrix** [comment]
@LinqLover I believe this is because the repo does not exist inside the `_downloaded` directory, and that moving the repo into this directory should resolve this issue :D
